
"""
Revision ID: cbb68b2a6885
Revises: 
Create Date: 2026-05-29 11:50:23.602465
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cbb68b2a6885'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
